name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
      PROD: ${{ secrets.PROD }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PATH: ${{ secrets.SERVER_PATH }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      #- name: Setup Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: ${{ matrix.node-version }}
      #    cache: yarn

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install --global yarn
          yarn install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          yarn install
          yarn build

      - name: Run Backend Tests
        working-directory: ./backend
        run: yarn test

      - name: Setup Backend .env
        working-directory: ./backend
        run: |
          echo "$PROD" > .env

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.SERVER_PATH }}
            git pull origin main
            cd backend
            yarn install --production
            echo "${PROD}" > .env
            pm2 restart all || pm2 start npm --name "backend" -- run start
            pm2 save
